### PR TITLE
We should have done that before... MUCH CLEANER !

### PR DESCRIPTION
**Pull request by Ad5001**
It uses XmlHttpRequests to access dfierent lessons so the main file is not surcharged. To add a lessons, add an article with the id of the lesson, a button in the menue, and a file with the name of the id and a .html.

Btw, I'm in the org but I can't commit here.

### CODE REVIEW

**Comment by Ad5001** [comment]
Btw preview is at http://serveur.cf/PluginTutorial

**Comment by keithkfng** [comment]
That looks a hell of a lot better...

**Comment by remotevase** [comment]
DAMN AWESOME! THANKS SO MUCH!

**Comment by remotevase** [comment]
I gotta use this for my other sites... Any link for how to implement?

**Comment by Ad5001** [comment]
Just implement the pages.js in the assets/js and add the script ;)

**Comment by remotevase** [comment]
Cool! Thanks!

**Comment by Taki21** [comment]
guys theres some mistakes lol

**Comment by Taki21** [comment]
u repeated commands volume twice

**Comment by keithkfng** [comment]
@Taki21 I don't think it's finished yet... for some reason there's a contact page...

**Comment by Ad5001** [comment]
Well, it seems random... Will try to fix that ASAP

**Comment by Ad5001** [comment]
I see, promblems with order of async. Will try to fix this.

**Comment by Taki21** [comment]
Also thanks for doing this new thingy with my lessons lol

and

can u tell @TheKnightGamer to gimme credit on pmmp forums? My account confirmation isnt working but anyways lol

**Comment by Taki21** [comment]
Dis thing
https://forums.pmmp.io/threads/plugin-tutorial-for-future-developers.25/

**Comment by keithkfng** [comment]
@Taki21 will do. He seems to take credit for everything...

**Comment by Taki21** [comment]
Lol @keithkfng thanks

**Comment by Taki21** [comment]
also do u guys know why i cant confirm my account?

**Comment by Ad5001** [comment]
You didn't receive the email?

**Comment by Taki21** [comment]
i did

**Comment by Taki21** [comment]
but it says error

**Comment by Ad5001** [comment]
Which one?

**Comment by Taki21** [comment]
one sec

**Comment by Taki21** [comment]
lemme pull up a screenshot

**Comment by Ad5001** [comment]
Ok.

**Comment by Taki21** [comment]
nvm

**Comment by Taki21** [comment]
I made a dumb mistake

**Comment by Taki21** [comment]
>_> Silly meh

**Comment by remotevase** [comment]
👍 @TheKnightGamer is annoying sometimes...

**Comment by keithkfng** [comment]
@Taki21 just to let you know that you have been demoted on IM because you are supposedly leaving for PC. Tell me if you want to be promoted anytime again :)

**Comment by remotevase** [comment]
@keithkfng see [this](https://github.com/Taki21/Taki21.github.io/issues/2)

**Comment by keithkfng** [comment]
@remotevase thanks.

**Comment by Taki21** [comment]
ok @keithkfng im totally fine with it!

**Comment by Taki21** [comment]
also im more on my youtube channel now lol

**Comment by Taki21** [comment]
and animating

**Comment by Taki21** [comment]
@keithkfng i just saw the forums... omg so beautiful!!! Im back kinda but ill be here weekly few times?

**Comment by remotevase** [comment]
:P YES!!!!!

**Comment by TheDragonRing** [comment]
YES PLEASE COME BACK!!!!! :D

**Comment by keithkfng** [comment]
@Taki21 Please do! Promoting right away :)

**Comment by Taki21** [comment]
Thamk u m8 :p

**Comment by Taki21** [comment]
Just remember im a random animator and a former retired professor

**Comment by Taki21** [comment]
Wow... while the new php lessons website was loading a black screen with code came on it and I was like oh no .... am i getting hacked? Then I realized... ooh thats the website backround lol

**Comment by TheKnightGamer** [comment]
Ok first thing I did not take any credit for anything if you saw the old post I had credit everyone and the thing @Ad5001 did I was going to do for @remote_vase and if you want me to take this thread down ( https://forums.pmmp.io/threads/plugin-tutorial-for-future-developers.25/ ) I will and I was not going to change the tutorials I was going to update the website not change everything.

**Comment by TheKnightGamer** [comment]
And I fell @remote_vase hate me

**Comment by TheKnightGamer** [comment]
@remotevase

**Comment by Taki21** [comment]
@TheKnightGamer no no dude we simply asked to put my name in the post because i am the original creator so da people dere would know :/
lol

**Comment by TheKnightGamer** [comment]
@taki21 I already give credits to you all and then when they start to reactive the project I changed it and said to myself I will put it when the project is finish.

**Comment by keithkfng** [comment]
@TheKnightGamer nobody cares what you said to yourself, just put it in now, not when it's finished...

**Comment by TheKnightGamer** [comment]
@keithfng I put it in and yeah I know nobody cares.

**Pull request merged**
